### ISSUE TITLE
Authentication no longer work due the InternalOAuthError

### ISSUE THREAD

**Issue by juhamust** [jaredhanson/passport-fitbit#3]
Authentication no longer work but following error is given:

```
InternalOAuthError: Failed to obtain request token 
(status: 401 data: {"errors":[{
"errorType":"oauth",
"fieldName":"oauth_timestamp",
"message":"oauth_acceptable_timestamps=1420057391-1420057991"
}],"success":false})
```

Not sure if related, but ```make test``` also fails:
```
✗ Errored » 1 errored

Makefile:11: recipe for target 'test' failed
make: *** [test] Error 1
```

Already tried upgrading out-dated (0.1.x) passport-oauth to 1.0.0, but it makes not difference.

**Comment by cquartier** [comment]
@juhamust I'd make sure whatever machine is running the code has the right date and time. Also that you aren't delaying the message through debugging (like stepping through code). This module still works fine for me, but it looks like the oauth timestamp you provided is out of range. Fitbit has a 600 second (10 minute) window of acceptable timestamps for a particular message. Your timestamp cannot be in the future relative to the server or it will be rejected. It also can't have a timestamp more than 10 minutes in the past relative to the server.

**Comment by juhamust** [comment]
Oh, thanks for pointing it out. I'll have to check. Do you have a minimal working example available somewhere (excluding the API token etc, of cource)? And any comments about the test - does it fail for you?

**Comment by cquartier** [comment]
I do not have a public working example but I can tell you my Amazon EC2 Linux server is using this library to handle the authentication and it still operates for my customers. Unfortunately there are changes needed to this library to bring it in line with authentication options that Fitbit gives you (and also to match the documentation). I submitted a pull request but I get the feeling @jaredhanson isn't maintaining this repo any longer, so I've recently switched to my own fork which has some needed updates for my own uses (cquartier/passport-fitbit)

**Comment by juhamust** [comment]
Good call with the timing! My setup was running a bit behind (15min), causing the issue. I wonder how I never noticed it earlier. After enabling the NTP, I was able to run example (found in the repo) successfully.

As for the module maintenance, there is some of that expected to be done in the near future as Fitbit is switching to OAuth2: https://wiki.fitbit.com/display/API/Fitbit+API
