### ISSUE TITLE
Publish latest version of passport-fitbit to npm

### ISSUE THREAD

**Issue by mbmccormick** [jaredhanson/passport-fitbit#6]
Now that @jeremiahlee has updated this package to use the new authorization URL, can you please bump the version and publish the new `passport-fitbit` package to npm?

Any applications that are using the `passport-fitbit` package are likely still using the old authorization URL unless they have offline version of the library. I've had to publish a clone of it myself and use my version of `passport-fitbit` for my applications.

https://www.npmjs.com/package/passport-fitbit

https://www.npmjs.com/package/passport-fitbit2

@jaredhanson should be able to manage collaborators for the npm package here: https://www.npmjs.com/package/passport-fitbit/access

**Comment by jaredhanson** [comment]
v1.1.0 is on npm.
